add datastream support
opensearch-project/opensearch-k8s-operator pull request #735
Opened 2024-02-22 10:55 UTC by cgroschupp

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-03-06 07:40 UTC, cthtrifork commented
Great! I would love this feature in the next coming release! (perhaps 2.5.2? https://github.com/opensearch-project/opensearch-k8s-operator/issues/749)

2024-03-15 11:58 UTC, cgroschupp commented
@cthtrifork As this is a new feature, I think the 2.3.0 version is better.

@idanl21 Can you please review this pull request?

2024-03-25 20:33 UTC, prudhvigodithi commented
Thanks @cgroschupp for your contribution, before we get this PR merged, can you please open an issue summarizing the datastream support in detail? This way your contribution is tracked in the issue and later we can link this PR to the issue.

Adding @bbarani @salyh @jochenkressin @pchmielnik @swoehrl-mw

2024-03-27 16:05 UTC, cgroschupp commented
@prudhvigodithi done

2024-04-04 18:29 UTC, prudhvigodithi commented
Hey @cgroschupp we can push this to `v2.6.0` https://github.com/opensearch-project/opensearch-k8s-operator/issues/776, can you please add unit tests to this change ?
Adding @swoehrl-mw @salyh @cthtrifork can you please add your review?
Thanks

2024-04-05 09:14 UTC, cgroschupp commented
@prudhvigodithi  done

2024-04-05 10:45 UTC, swoehrl-mw requested changes
One gripe about naming, everything else looks good

2024-04-05 10:45 UTC, swoehrl-mw commented on opensearch-operator/api/v1/opensearch_index_types.go
> +	TimestampField OpensearchDatastreamTimestampFieldSpec `json:"timestamp_field,omitempty"`
Every other field is camelCase, so this should as well to be consistent

2024-04-05 11:10 UTC, swoehrl-mw requested changes

2024-04-05 11:10 UTC, swoehrl-mw commented on opensearch-operator/api/v1/opensearch_index_types.go
> +	TimestampField OpensearchDataStreamTimestampFieldSpec `json:"timestamp_field,omitempty"`
Sorry for not being clearer, my camelCase comment was primarily aimed at `timestamp_field` (should be `timestampField`). Even though in the opensearch api it is snake_case, the operator CRDs use camelCase all around

2024-04-05 12:14 UTC, swoehrl-mw approved these changes

2024-04-05 12:15 UTC, merged