Update Operator compatibility matrix and honor compatibility for functional tests
opensearch-project/opensearch-k8s-operator pull request #792
Opened 2024-04-25 19:05 UTC by prudhvigodithi

### Description
Update Operator compatibility matrix and honor compatibility for functional tests 

### Issues Resolved
Coming from https://github.com/opensearch-project/opensearch-k8s-operator/issues/776#issuecomment-2072921621

### Check List
- [ ] Commits are signed per the DCO using --signoff 
- [ ] Unittest added for the new/changed functionality and all unit tests are successful
- [ ] Customer-visible features documented
- [ ] No linter warnings (`make lint`)

If CRDs are changed:
- [ ] CRD YAMLs updated (`make manifests`) and also copied into the helm chart
- [ ] Changes to CRDs documented

Please refer to the [PR guidelines](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/developing.md#submitting-a-pr) before submitting this pull request.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-26 07:59 UTC, salyh requested changes
Pls add "Fixes https://github.com/opensearch-project/opensearch-k8s-operator/issues/760"

2024-04-26 15:19 UTC, prudhvigodithi commented
> Pls add "Fixes #760"

Thanks and updated @salyh.

2024-05-13 15:56 UTC, prudhvigodithi commented
@salyh I have updated the PR to have the compatibility matrix updated for the versions released that are part of the [OpenSearch Project org](https://github.com/opensearch-project/). Please check.
Adding @swoehrl-mw @dtaivpp @bbarani

2024-05-13 17:40 UTC, salyh approved these changes

2024-05-13 17:44 UTC, merged