Add the capability to use RoleBindings instead of ClusterRoleBindings
opensearch-project/opensearch-k8s-operator pull request #841
Opened 2024-06-08 18:00 UTC by nilushancosta

### Description
This PR introduces a new key to the Helm values named `useRoleBindings` which when set to `true` creates Kubernetes RoleBindings instead of ClusterRoleBindings

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-k8s-operator/issues/831

### Check List
- [x] Commits are signed per the DCO using --signoff 
- [ ] Unittest added for the new/changed functionality and all unit tests are successful
- [x] Customer-visible features documented
- [ ] No linter warnings (`make lint`)

If CRDs are changed:
- [ ] CRD YAMLs updated (`make manifests`) and also copied into the helm chart
- [ ] Changes to CRDs documented

Please refer to the [PR guidelines](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/developing.md#submitting-a-pr) before submitting this pull request.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-03 10:39 UTC, nilushancosta commented
@swoehrl-mw would you be able to have a look at this PR?

2024-10-17 17:27 UTC, nilushancosta commented
> I think it makes more sense to have the ClusterRoleBinding and the RoleBinding in the same file (without the `-crb` in the filename to make it more generic) and use an if-else-end construct.

@swoehrl-mw I changed it as requested

2024-10-18 08:10 UTC, swoehrl-mw requested changes

2024-10-18 08:10 UTC, swoehrl-mw commented on charts/opensearch-operator/templates/opensearch-operator-manager-rolebinding.yaml
> +  name: {{ include "opensearch-operator.fullname" . }}-{{ .Release.Namespace }}-manager-cluster-rolebinding
```suggestion
  name: {{ include "opensearch-operator.fullname" . }}-{{ .Release.Namespace }}-manager-rolebinding
```

Name should stay the same as it is now, IMO it is also not a problem if rolebinding and clusterrolebinding are named the same

2024-10-18 08:10 UTC, swoehrl-mw commented on charts/opensearch-operator/templates/opensearch-operator-proxy-rolebinding.yaml
> +  name: {{ include "opensearch-operator.fullname" . }}-{{ .Release.Namespace }}-proxy-cluster-rolebinding
```suggestion
  name: {{ include "opensearch-operator.fullname" . }}-{{ .Release.Namespace }}-proxy-rolebinding
```

2024-10-29 12:28 UTC, swoehrl-mw approved these changes

2024-10-29 12:28 UTC, merged