Decouple Helm Release with the Operator Release
opensearch-project/opensearch-k8s-operator pull request #872
Opened 2024-09-17 17:08 UTC by prudhvigodithi

### Description
Decouple Helm Release with the Operator Release

### Issues Resolved
Coming from https://github.com/opensearch-project/opensearch-k8s-operator/issues/830

### Check List
- [ ] Commits are signed per the DCO using --signoff 
- [ ] Unittest added for the new/changed functionality and all unit tests are successful
- [ ] Customer-visible features documented
- [ ] No linter warnings (`make lint`)

If CRDs are changed:
- [ ] CRD YAMLs updated (`make manifests`) and also copied into the helm chart
- [ ] Changes to CRDs documented

Please refer to the [PR guidelines](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/developing.md#submitting-a-pr) before submitting this pull request.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-17 17:16 UTC, prudhvigodithi commented
Adding @swoehrl-mw and @evheniyt to please take a look, once this is merged we can move forward with this PR https://github.com/opensearch-project/opensearch-k8s-operator/pull/754 to refactor opensearch-cluster helm chart. 

Once this PR is merged the idea is to rebase this PR https://github.com/opensearch-project/opensearch-k8s-operator/pull/754, update the `version` and merge to `main`, then the `helm/chart-releaser-action` will take care of releasing the helm chart.

Thank you 
@getsaurabh02 @peterzhuamazon

2024-09-17 19:04 UTC, peterzhuamazon approved these changes
So basically helm will always be latest HEAD?
While operator official release will be stable ones?

Thanks.

2024-09-17 21:04 UTC, prudhvigodithi commented
> So basically helm will always be latest HEAD? While operator official release will be stable ones?
> 
> Thanks.

Thanks Peter, the operator when released creates the docker image and other helm charts (the seperate releases) uses this operator version from `appVersion`. 

It is the same mechanism that we use today for OpenSearch helm charts https://github.com/opensearch-project/helm-charts/pull/569 where the `appVersion` is the OpenSearch version.

2024-09-19 12:59 UTC, swoehrl-mw requested changes
I'm fine with doing this for the opensearch-cluster helm chart and can see the advantages of having a faster release cycle.
But for the opensearch-operator chart this is a problem with the current development process: If an operator feature requires changes to the chart (e.g. a new config option or changes to one of the CRDs) these are made in the same PR as the code changes. With this new release process we run a huge risk of releasing features in the chart that are not yet included in the operator code if someone makes a non-related change in the chart and wants to release that by increasing the version. This will only lead to problems.
So IMO the release and version of the operator chart should stay coupled with the operator release.


Also: You at least need to extend the `CONTRIBUTING.md` and `docs/developing.md` to explain the process, that users need to edit the changelog and how and when to increase helm chart versions.

2024-09-19 14:53 UTC, prudhvigodithi commented
> With this new release process we run a huge risk of releasing features in the chart that are not yet included in the operator code if someone makes a non-related change in the chart and wants to release that by increasing the version. This will only lead to problems.
> So IMO the release and version of the operator chart should stay coupled with the operator release.

Thanks, @swoehrl-mw. I agree with your point, but I believe the maintainers are responsible for reviewing PRs and Helm chart changes. For example, in this PR https://github.com/opensearch-project/opensearch-k8s-operator/pull/754/files, the change involved the `opensearch-cluster`, and the maintainers should be aware of code modifications made to the `opensearch-operator` Helm chart and decide if the chart version needs to be incremented. 

This PR aims to standardize the Helm release process for both `opensearch-cluster` and `opensearch-operator` Helm charts, which would only require a version increment, and the workflow would handle the release. The timing and coordination of version increments should be managed by the PR authors and maintainers to ensure smooth chart releases. 

In some cases, like a critical/small fix, we may need to release the `opensearch-operator` Helm chart independently, without waiting for the `opensearch-operator` release and this process (by this PR) should be helpful and unblock the chart release.

Thank you 
Adding @getsaurabh02 @salyh @pchmielnik @jochenkressin @dblock @peterzhuamazon

2024-09-20 15:35 UTC, prudhvigodithi commented
@swoehrl-mw any other suggestions on how to move forward with this PR https://github.com/opensearch-project/opensearch-k8s-operator/pull/754 without decoupling the releases?

> that is not really an argument for me.

Again we cant release an operator for every small change in the helm chart (and helm chart should not wait until the operator is released), IMO its totally worth to decouple both the 2 products, the operator and the helm chart.

2024-09-23 19:56 UTC, prudhvigodithi commented
Following, @swoehrl-mw can you please suggest the next steps here? I want to Decouple Helm Release with the Operator Release because of https://github.com/opensearch-project/opensearch-k8s-operator/pull/872#issuecomment-2364003894 and unblock the PR https://github.com/opensearch-project/opensearch-k8s-operator/pull/754.
Thank you 
@getsaurabh02 @peterzhuamazon

2024-09-24 14:19 UTC, swoehrl-mw commented
@prudhvigodithi I would suggest to have the opensearch-cluster helm chart with the release process as you suggest it in this PR and have operator docker + opensearch-operatorhelm chart with the release process as it is currently. That way #754 would be unblocked. Releases for the operator chart would still be slow, but as I said in an earlier comment that chart is tightly coupled with operator features so they should really be released only together.

2024-10-28 14:00 UTC, evheniyt commented
@prudhvigodithi for me this sounds reasonable, could we start moving forward with decoupling for opensearch-cluster?

2024-11-04 20:11 UTC, prudhvigodithi commented
Sure @evheniyt let me finalize the PR with just decoupling `opensearch-cluster` helm chart.

2024-11-04 20:35 UTC, prudhvigodithi commented
Coming from https://github.com/helm/chart-releaser?tab=readme-ov-file#dealing-with-charts-that-have-dependencies leveraged `charts_dir` to release opensearch-operator helm chart with the common operator release and opensearch-cluster on merge to `main` with version increment.

2024-11-04 21:13 UTC, peterzhuamazon approved these changes

2024-11-04 21:13 UTC, peterzhuamazon commented on .github/workflows/release.yaml
> +
Extra spacing?

2024-11-05 14:01 UTC, swoehrl-mw approved these changes

2024-11-05 14:10 UTC, merged